#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/../ci/utils.sh"

# PLEASE READ:
#
# The FMF tests deploy the FDO servers via RPM packages. These
# packages are either provided by the Packit service or pulled from
# the fedora-iot COPR repository.
#
# The server RPMs install default configuration files and systemd
# services for running the servers.  In addition example server
# certificates and key files are generated by a systemd service on
# service startup.
#
# In order to provide proper test coverage of the RPM packaging,
# default configurations, systemd operation and example certificates,
# tests in this directory SHOULD use these defaults whenever possible.
#
# If a test requires a custom configuration consider the following
# recommendations:
#
# o) A home directory is created for each server at the start of the
# test for scratch data. This directory is automatically cleaned up at
# the end of the test. This directory path is
# `rpm_${service}_home_dir`
#
# o) To create a custom configuration file define a
# `configure_service_${service}()` function that overrides the
# configuration variables defined below then invokes the helper
# function `generate_${service}_config()` to write the configuration
# to a file. This file will be saved in a directory that takes
# precedence over the default in the server's configuration search
# path. The configuration file is automatically deleted at the end of
# the test.
#
# o) To pass command line arguments to the server create a systemd
# "drop-in" file that overrides the ExecStart= setting in the service
# file. This drop-in file should be placed in the directory defined by
# the variable `systemd_${service}_drop_in_dir`.  Remember to run
# `sudo systemctl daemon-reload` after writing the drop-in file.

#shellcheck disable=SC2034
rpm_config_base_dir="/etc/go-fdo-server"  # RPMs install the default configs here
rpm_certs_dir="/etc/pki/go-fdo-server"    # RPMs generate the default certs/keys
rpm_group="go-fdo-server"

rpm_device_ca_crt="${rpm_certs_dir}/device-ca-example.crt"
rpm_device_ca_key="${rpm_certs_dir}/device-ca-example.key"

rpm_manufacturer_user="go-fdo-server-manufacturer"
rpm_manufacturer_home_dir="/run/go-fdo-server-manufacturer"
rpm_manufacturer_config_dir="${rpm_manufacturer_home_dir}/.config/go-fdo-server"
rpm_manufacturer_config_file="${rpm_manufacturer_config_dir}/manufacturing.yaml"
rpm_manufacturer_db_type="sqlite"
rpm_manufacturer_database_dir="/var/lib/go-fdo-server-manufacturer"
rpm_manufacturer_db_dsn="file:${rpm_manufacturer_database_dir}/db.sqlite"
rpm_manufacturer_key="${rpm_certs_dir}/manufacturer-example.key"
#shellcheck disable=SC2034
rpm_manufacturer_crt="${rpm_certs_dir}/manufacturer-example.crt"
rpm_manufacturer_log_level="debug"
rpm_manufacturer_http_ip="0.0.0.0"
rpm_manufacturer_http_port="8038"
rpm_manufacturer_https_key="${rpm_manufacturer_home_dir}/manufacturer-https-example.key"
rpm_manufacturer_https_crt="${rpm_manufacturer_home_dir}/manufacturer-https-example.crt"

rpm_rendezvous_user="go-fdo-server-rendezvous"
rpm_rendezvous_home_dir="/run/go-fdo-server-rendezvous"
rpm_rendezvous_config_dir="${rpm_rendezvous_home_dir}/.config/go-fdo-server"
rpm_rendezvous_config_file="${rpm_rendezvous_config_dir}/rendezvous.yaml"
rpm_rendezvous_db_type="sqlite"
rpm_rendezvous_database_dir="/var/lib/go-fdo-server-rendezvous"
rpm_rendezvous_db_dsn="file:${rpm_rendezvous_database_dir}/db.sqlite"
rpm_rendezvous_log_level="debug"
rpm_rendezvous_http_ip="0.0.0.0"
rpm_rendezvous_http_port="8041"
rpm_rendezvous_https_key="${rpm_rendezvous_home_dir}/rendezvous-https-example.key"
rpm_rendezvous_https_crt="${rpm_rendezvous_home_dir}/rendezvous-https-example.crt"

rpm_owner_user="go-fdo-server-owner"
rpm_owner_home_dir="/run/go-fdo-server-owner"
rpm_owner_config_dir="${rpm_owner_home_dir}/.config/go-fdo-server"
rpm_owner_config_file="${rpm_owner_config_dir}/owner.yaml"
rpm_owner_db_type="sqlite"
rpm_owner_database_dir="/var/lib/go-fdo-server-owner"
rpm_owner_db_dsn="file:${rpm_owner_database_dir}/db.sqlite"
rpm_owner_key="${rpm_certs_dir}/owner-example.key"
rpm_owner_crt="${rpm_certs_dir}/owner-example.crt"
rpm_owner_log_level="debug"
rpm_owner_http_ip="0.0.0.0"
rpm_owner_http_port="8043"
rpm_owner_reuse_creds="false"
rpm_owner_to0_insecure_tls="false"
rpm_owner_https_key="${rpm_owner_home_dir}/owner-https-example.key"
rpm_owner_https_crt="${rpm_owner_home_dir}/owner-https-example.crt"

# systemd drop-in file configuration
#
systemd_drop_in_base_dir="/run/systemd/system"
#shellcheck disable=SC2034
systemd_manufacturer_drop_in_dir="${systemd_drop_in_base_dir}/go-fdo-server-manufacturer.service.d"
#shellcheck disable=SC2034
systemd_rendezvous_drop_in_dir="${systemd_drop_in_base_dir}/go-fdo-server-rendezvous.service.d"
#shellcheck disable=SC2034
systemd_owner_drop_in_dir="${systemd_drop_in_base_dir}/go-fdo-server-owner.service.d"


generate_manufacturer_config() {
  sudo rm -f "${rpm_manufacturer_config_file}"
  sudo mkdir -p "${rpm_manufacturer_config_dir}"
  sudo tee "${rpm_manufacturer_config_file}" <<EOF1
log:
  level: "${rpm_manufacturer_log_level}"
db:
  type: "${rpm_manufacturer_db_type}"
  dsn: "${rpm_manufacturer_db_dsn}"
manufacturing:
  key: "${rpm_manufacturer_key}"
device_ca:
  cert: "${rpm_device_ca_crt}"
  key: "${rpm_device_ca_key}"
owner:
  cert: "${rpm_owner_crt}"
http:
  ip: "${rpm_manufacturer_http_ip}"
  port: "${rpm_manufacturer_http_port}"
EOF1
  # Enable HTTP if https protocol is used
  if [ "${manufacturer_protocol}" = "https" ]; then
    sudo tee -a "${rpm_manufacturer_config_file}" <<EOF2
  cert: "${rpm_manufacturer_https_crt}"
  key: "${rpm_manufacturer_https_key}"
EOF2
  fi
  sudo chown -R ${rpm_manufacturer_user}:${rpm_group} ${rpm_manufacturer_config_dir}
}

generate_rendezvous_config() {
  sudo rm -f "${rpm_rendezvous_config_file}"
  sudo mkdir -p "${rpm_rendezvous_config_dir}"
  sudo tee "${rpm_rendezvous_config_file}" <<EOF1
log:
  level: "${rpm_rendezvous_log_level}"
db:
  type: "${rpm_rendezvous_db_type}"
  dsn: "${rpm_rendezvous_db_dsn}"
http:
  ip: "${rpm_rendezvous_http_ip}"
  port: "${rpm_rendezvous_http_port}"
EOF1
  # Enable HTTP if https protocol is used
  if [ "${rendezvous_protocol}" = "https" ]; then
    sudo tee -a "${rpm_rendezvous_config_file}" <<EOF2
  cert: "${rpm_rendezvous_https_crt}"
  key: "${rpm_rendezvous_https_key}"
EOF2
  fi
  sudo chown -R ${rpm_rendezvous_user}:${rpm_group} ${rpm_rendezvous_config_dir}
}

generate_owner_config() {
  sudo rm -f "${rpm_owner_config_file}"
  sudo mkdir -p "${rpm_owner_config_dir}"
  sudo tee "${rpm_owner_config_file}" <<EOF1
log:
  level: "${rpm_owner_log_level}"
db:
  type: "${rpm_owner_db_type}"
  dsn: "${rpm_owner_db_dsn}"
device_ca:
  cert: "${rpm_device_ca_crt}"
owner:
  cert: "${rpm_owner_crt}"
  key: "${rpm_owner_key}"
  reuse_credentials: "${rpm_owner_reuse_creds}"
  to0_insecure_tls: "${rpm_owner_to0_insecure_tls}"
http:
  ip: "${rpm_owner_http_ip}"
  port: "${rpm_owner_http_port}"
EOF1
  # Enable HTTP if https protocol is used
  if [ "${owner_protocol}" = "https" ]; then
    sudo tee -a "${rpm_owner_config_file}" <<EOF2
  cert: "${rpm_owner_https_crt}"
  key: "${rpm_owner_https_key}"
EOF2
  fi
  sudo chown -R ${rpm_owner_user}:${rpm_group} ${rpm_owner_config_dir}
}

install_from_copr() {
  rpm -q --whatprovides 'dnf-command(copr)' &> /dev/null || sudo dnf install -y 'dnf-command(copr)'
  dnf copr list | grep 'fedora-iot/fedora-iot' || sudo dnf copr enable -y @fedora-iot/fedora-iot
  # testing-farm-tag-repository is causing problems with builds see:
  # https://docs.testing-farm.io/Testing%20Farm/0.1/test-environment.html#disabling-tag-repository
  sudo dnf install -y "$@"
  sudo dnf copr disable -y @fedora-iot/fedora-iot
}

install_client() {
  # If PACKIT_COPR_RPMS is not defined it means we are running the test
  # locally so we will install the client from the copr repo
  [ -v "PACKIT_COPR_RPMS" ] || rpm -q go-fdo-client &> /dev/null || install_from_copr go-fdo-client
}

uninstall_client() {
  # When running a test locally we remove the client package
  # after a successful execution.
  [ -v "PACKIT_COPR_RPMS" ] || {
    sudo dnf remove -y go-fdo-client;
    sudo dnf copr remove -y @fedora-iot/fedora-iot;
  }
}

install_server() {
  # If PACKIT_COPR_RPMS is not defined it means we are running the test
  # locally so we will build and install the RPMs
  if [ ! -v "PACKIT_COPR_RPMS" ]; then
    commit="$(git rev-parse --short HEAD)"
    rpm -q go-fdo-server | grep -q "go-fdo-server.*git${commit}.*" || { \
      make rpm;
      sudo dnf install -y rpmbuild/rpms/{noarch,"$(uname -m)"}/*git"${commit}"*.rpm;
    }
  else
    echo "  - Expected RPMs:  ${PACKIT_COPR_RPMS}"
  fi
  # Make sure the RPMS are installed
  installed_rpms=$(rpm -q --qf "%{nvr}.%{arch} " go-fdo-server{,-{manufacturer,owner,rendezvous}})
  echo "  - Installed RPMs: ${installed_rpms}"

  # Cleanup any stale test configuration
  cleanup_drop_ins
  cleanup_databases
  cleanup_home_dirs

  log_info "Creating server home directories"
  setup_home_dirs
}

uninstall_server() {
  [ -v "PACKIT_COPR_RPMS" ] || sudo dnf remove -y go-fdo-server{,-manufacturer,-owner,-rendezvous}
}

start_service_manufacturer() {
  sudo systemctl start go-fdo-server-manufacturer
}

start_service_rendezvous() {
  sudo systemctl start go-fdo-server-rendezvous
}

start_service_owner() {
  sudo systemctl start go-fdo-server-owner
}

# We do not use pid files but functions to stop the services via systemctl
stop_service() {
  local service=$1
  local stop_service="stop_service_${service}"
  ! declare -F "${stop_service}" >/dev/null || ${stop_service}
}

stop_service_manufacturer() {
  sudo systemctl stop go-fdo-server-manufacturer
}

stop_service_rendezvous() {
  sudo systemctl stop go-fdo-server-rendezvous
}

stop_service_owner() {
  sudo systemctl stop go-fdo-server-owner
}

get_go_fdo_server_logs() {
  local role=$1
  journalctl_args=("--no-pager" "--output=cat" "--unit" "go-fdo-server-${role}")
  . /etc/os-release
  [[ "${ID}" = "centos" && "${VERSION_ID}" = "9" ]] || journalctl_args+=("--invocation=0")
  systemctl status "go-fdo-server-${role}.service" || true
  journalctl "${journalctl_args[@]}"
}

get_service_logs_manufacturer() {
  get_go_fdo_server_logs manufacturer
}

get_service_logs_rendezvous() {
  get_go_fdo_server_logs rendezvous
}

get_service_logs_owner() {
  get_go_fdo_server_logs owner
}

get_service_logs() {
  local service=$1
  log "🛑 '${service}' logs:\n"
  local get_service_logs_func="get_service_logs_${service}"
  ! declare -F "${get_service_logs_func}" >/dev/null || ${get_service_logs_func}
}

save_go_fdo_server_logs() {
  local role=$1
  local log_file=$2
  get_go_fdo_server_logs "${role}" > "${log_file}"
}

save_service_logs_manufacturer() {
  save_go_fdo_server_logs manufacturer "${manufacturer_log}"
}

save_service_logs_rendezvous() {
  save_go_fdo_server_logs rendezvous "${rendezvous_log}"
}

save_service_logs_owner() {
  save_go_fdo_server_logs owner "${owner_log}"
}

save_service_logs() {
  local service=$1
  log "\t⚙ Saving '${service}' logs "
  local save_service_logs_func="save_service_logs_${service}"
  ! declare -F "${save_service_logs_func}" >/dev/null || ${save_service_logs_func}
  log_success
}

save_logs() {
  log_info "Saving logs"
  for service in "${services[@]}"; do
    save_service_logs ${service}
  done
  if [ -v "PACKIT_COPR_RPMS" ]; then
    log_info "Submitting files to TMT '${base_dir:?}'"
    find "${base_dir:?}" -type f -exec tmt-file-submit -l {} \;
  fi
}

setup_home_dirs() {
  for server in rendezvous manufacturer owner; do
    local homedir_var="rpm_${server}_home_dir"
    local user_var="rpm_${server}_user"
    sudo mkdir -p "${!homedir_var:?}"
    sudo chown -R "${!user_var:?}:${rpm_group}" "${!homedir_var:?}"
  done
}

cleanup_home_dirs() {
  for server in rendezvous manufacturer owner; do
    local homedir_var="rpm_${server}_home_dir"
    sudo rm -vrf "${!homedir_var:?}"
  done
}

cleanup_databases() {
  for server in rendezvous manufacturer owner; do
    local dbdir_var="rpm_${server}_database_dir"
    if [[ -v "${dbdir_var}" ]]; then
      sudo rm -vf "${!dbdir_var:?}"/*
    fi
  done
}

cleanup_drop_ins() {
  local reload_systemd=0
  for service in rendezvous manufacturer owner; do
    local drop_in_dir_var="systemd_${service}_drop_in_dir"
    if [[ -d "${!drop_in_dir_var}" ]]; then
      reload_systemd=1
      sudo rm -vf "${!drop_in_dir_var:?}"/*
    fi
  done
  if [[ ${reload_systemd} -eq 1 ]]; then
    sudo systemctl daemon-reload
  fi
}

remove_files() {
  log_info "Removing files from '${base_dir:?}'"
  sudo rm -vrf "${base_dir:?}"/*
  log_info "Removing files from '${rpm_certs_dir}'"
  sudo rm -vf "${rpm_certs_dir:?}/"*
  log_info "Removing systemd drop-in files"
  cleanup_drop_ins
  log_info "Removing database files"
  cleanup_databases
  log_info "Removing server home directories"
  cleanup_home_dirs
}

on_failure() {
  trap - ERR
  save_logs
  stop_services
  test_fail
}

cleanup() {
  [ ! -v "PACKIT_COPR_RPMS" ] || save_logs
  stop_services
  unset_hostnames
  uninstall_server
  uninstall_client
  remove_files
}
